### ISSUE TITLE
SPI and I2C LCD drivers broken

### ISSUE THREAD

**Issue by dvosully** [espressif/esp-iot-solution#225]
Environment: Any ESP module using any SPI graphic display which uses the LCD drivers in [components/display/screen/screen_utility/] on any platform. The one that broke for me was the ILI9341 driver.

To replicate: Run any of the hmi examples, eg. examples/hmi/lvgl_coffee/

SPI (and presumably I2C) LCD drivers were broken by commit https://github.com/espressif/esp-iot-solution/commit/0caa2de5567a17507bc9f542d0bf212637cf3efe

The regression causes the screen initialisation to fail upon any attempt to write to the display. The initialisation code attempts to call the NULL pointer contained by g_lcd_handle.interface_drv->write_command because the SPI drivers which depend on the screen_utility were never modified to match the new interface.

The commit changed the components/display/screen/screen_utility/interface_drv_def.h API without updating the existing drivers using the API. Specifically, the SPI drivers call the LCD_WRITE_CMD() macro; This previously remapped to the interface_drv->write_cmd function which existed.
The change introduced a new macro, LCD_WRITE_COMMAND() which is a variable length version of LCD_WRITE_CMD(), which remapped to the new function interface_drv->write_command. The LCD_WRITE_CMD() macro was changed to reference the LCD_WRITE_COMMAND() macro, which for the SPI and I2C drivers calls a non-existent function. The write_cmd function was left dangling, never used.

See PR #171 for a proposed fix.

Properly, I figure all the LCD drivers should either get updated to instate the generic length write_command, and restore use of the write_data function, or the now dangling write_data function https://github.com/dvosully/esp-iot-solution/blob/611cca278ad25a321134cf502bcdb42c2ef2f26f/components/display/screen/interface_driver/scr_interface_driver.h#L67 should be removed entirely. Doing this would at least have thrown a compilation error on the breaking change.

**Comment by dvosully** [comment]
This was fixed in https://github.com/espressif/esp-iot-solution/commit/7a0eee234e95bb7b9d45136e09194715cf65476e

Missed that when following up. Sorry guys.
