### ISSUE TITLE
usb_stream 1.5.1 build fail with IDF 5.5.1 (AEGHB-1329)

### ISSUE THREAD

**Issue by SeByDocKy** [espressif/esp-iot-solution#620]
### Answers checklist.

- [x] I have read the documentation [ESP-IDF Programming Guide](https://docs.espressif.com/projects/esp-idf/en/latest/) and the issue is not addressed there.
- [x] I have updated my IDF branch (master or release) to the latest version and checked that the issue is present there.
- [x] I have searched the issue tracker for a similar issue and not found a similar issue.

### IDF version.

5.5.1

### Espressif SoC revision.

ESP32 S3

### Operating System used.

Windows

### How did you build your project?

Command line with Make

### If you are using Windows, please specify command line type.

None

### Development Kit.

esp32-s3-devkitc-1

### Steps to reproduce.

Building esphome example : https://github.com/anton-malakhov/esphome_webcam  built over 5.5.1
...

### Build Logs.

```plain
*** [.pioenvs\esp-webcam\managed_components\usb_stream\usb_host_helpers.c.o] Error 1
managed_components\usb_stream\usb_stream.c:515:5: error: unknown type name 'hcd_port_fifo_bias_t'; did you mean 'hcd_port_config_t'?
  515 |     hcd_port_fifo_bias_t fifo_bias;
      |     ^~~~~~~~~~~~~~~~~~~~
      |     hcd_port_config_t
In file included from C:\Users\sebyd\.platformio\packages\framework-espidf\components\esp_hw_support\include/esp_intr_alloc.h:12,
                 from C:\Users\sebyd\.platformio\packages\framework-espidf\components\esp_hw_support\include/esp_cpu.h:21,
                 from C:\Users\sebyd\.platformio\packages\framework-espidf\components\esp_hw_support\include/spinlock.h:11,
                 from C:\Users\sebyd\.platformio\packages\framework-espidf\components\freertos\FreeRTOS-Kernel\portable\xtensa\include\freertos/portmacro.h:49,
                 from C:\Users\sebyd\.platformio\packages\framework-espidf\components\freertos\FreeRTOS-Kernel\include/freertos/portable.h:57,
                 from C:\Users\sebyd\.platformio\packages\framework-espidf\components\freertos\FreeRTOS-Kernel\include/freertos/FreeRTOS.h:69,
                 from managed_components\usb_stream\usb_stream.c:14:
managed_components\usb_stream\usb_stream.c: In function '_usb_processing_task':
managed_components\usb_stream\usb_stream.c:3355:29: error: implicit declaration of function 'hcd_port_set_fifo_bias' [-Wimplicit-function-declaration]
 3355 |             ESP_ERROR_CHECK(hcd_port_set_fifo_bias(usb_dev->port_hdl, usb_dev->fifo_bias));
      |                             ^~~~~~~~~~~~~~~~~~~~~~
C:\Users\sebyd\.platformio\packages\framework-espidf\components\esp_common\include/esp_err.h:116:30: note: in definition of macro 'ESP_ERROR_CHECK'
  116 |         esp_err_t err_rc_ = (x);                                        \
      |                              ^
managed_components\usb_stream\usb_stream.c: In function 'usb_streaming_start':
managed_components\usb_stream\usb_stream.c:3707:27: error: 'HCD_PORT_FIFO_BIAS_BALANCED' undeclared (first use in this function)
 3707 |     s_usb_dev.fifo_bias = HCD_PORT_FIFO_BIAS_BALANCED;
      |                           ^~~~~~~~~~~~~~~~~~~~~~~~~~~
managed_components\usb_stream\usb_stream.c:3707:27: note: each undeclared identifier is reported only once for each function it appears in
managed_components\usb_stream\usb_stream.c:3761:31: error: 'HCD_PORT_FIFO_BIAS_RX' undeclared (first use in this function)
 3761 |         s_usb_dev.fifo_bias = HCD_PORT_FIFO_BIAS_RX;
```

**Comment by YanKE01** [comment]
Hi, @SeByDocKy . Please switch to Release V5.5 and then perform the test again.

**Comment by Talha-DPL** [comment]
Hi @YanKE01, i am using V5.5.2 and having the same issue. It was working fine with V5.4 and when i updated i am having this issue.

**Comment by SeByDocKy** [comment]
Yes neither V5.5.1 or V5.5.2 fixed the problem....

**Comment by TDA-2030** [comment]
In fact, usb_stream is being deprecated, and new projects recommend using [UAC](https://github.com/espressif/esp-usb/tree/master/host/class/uac/usb_host_uac) and [UVC](https://github.com/espressif/esp-usb/tree/master/host/class/uvc/usb_host_uvc) as its replacements.

**Comment by Talha-DPL** [comment]
Hey @TDA-2030, 

Thanks for the response. You mean we can remove the iot_usbh  component and use API form esp-idf itself now? 

One more thing is there any chance that we will update iot_usbh component for latest version?

**Comment by TDA-2030** [comment]
> You mean we can remove the iot_usbh component and use API form esp-idf itself now?

Yes

> One more thing is there any chance that we will update iot_usbh component for latest version?

The iot_usbh component is also about to be deprecated. New projects are advised to use https://github.com/espressif/esp-usb/tree/master/host/usb

**Comment by Talha-DPL** [comment]
> The iot_usbh component is also about to be deprecated. New projects are advised to use https://github.com/espressif/esp-usb/tree/master/host/usb


Hello @TDA-2030,
Thanks for your response. We are currently using iot_usbh indirectly through iot_usbh_cdc, which is further used by iot_usbh_modem. Since iot_usbh is being deprecated, what is the recommended migration path for projects that rely on the CDC + modem stack? Is there an official replacement or reference implementation using esp-usb/host/usb?
